Blog post about the FullInliner bug in 0.8.21
ethereum/solidity-website pull request #11
Opened 2023-07-17 12:52 UTC by cameel

2023-07-17 14:11 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The bug has "high" severity in affected cases, but we deem the likelihood of it actually affecting deployed contracts as "very low".
Should it be high severity + very low likelihood? Or maybe something like high + low? We only really agreed on the overall score.

2023-07-17 14:13 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +```
Note that these examples do no show actual compiler output. It's only meant to approximately illustrate what the step does.

2023-07-18 09:11 UTC, nikola-matic commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +When faced with code like this, `FullInliner`'s heuristics were supposed prevent inlining.
A nit pick regarding terminology: I don't think `heuristics` is the right name for this; it was supposed to be a hard rule that functions with function call arguments were not to be inlined (bug). Heuristics generally imply a more loosey-goosey trial and error approximate approach. In fact, I'd argue that the `FullInliner` steps uses absolutely no heuristics - it's literally just a set of hard rules, and not much else, no?

2023-07-18 09:11 UTC, nikola-matic commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Morevoer, the bug will not affect vast majority of Soldity code.
```suggestion
Morevoer, the bug will not affect the vast majority of Solidity code, if any.
```

2023-07-18 09:11 UTC, nikola-matic commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Code most likely to be broken by it is inline assembly, which normally constitutes a small
```suggestion
Code most likely to be broken by it, is inline assembly, which normally constitutes a small
```

2023-07-18 09:11 UTC, nikola-matic commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Therefore, while the bug can have severe consequences, we think that the overall impact on real
```suggestion
Therefore, while this bug can have severe consequences, we think that the overall impact on real
```

2023-07-18 09:32 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The bug has "high" severity in affected cases, but we deem the likelihood of it actually affecting deployed contracts as "very low".
Did we actually agree on likelihood?

Note that what I put in text was actually "very low".

2023-07-18 09:34 UTC, nikola-matic commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The bug has "high" severity in affected cases, but we deem the likelihood of it actually affecting deployed contracts as "very low".
I'd say it's very low, but then I don't really know which scale we used before, i.e. how coarse/fine grained it is? high medium low, or very high, high, medium, low, very low, etc? I'm personally fine with `very low`, but in that case we'll have to change the very last line of the blog post to reflect that as well (since there, it's `low if I remember correctly).

2023-07-18 09:40 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Morevoer, the bug will not affect vast majority of Soldity code.
I don't think "if any" is warranted here. The point is that it will not affect most code other than inline assembly and inline assembly is not that rare. It's just usually a small part of the code.

2023-07-18 09:42 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Code most likely to be broken by it is inline assembly, which normally constitutes a small
Why would you put a comma here? It adds a stop at a really weird point in the sentence.

2023-07-18 09:42 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Therefore, while the bug can have severe consequences, we think that the overall impact on real
Why?

2023-07-18 09:50 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +When faced with code like this, `FullInliner`'s heuristics were supposed prevent inlining.
But that's how we refer to those rules: https://github.com/ethereum/solidity/blob/v0.8.20/libyul/optimiser/FullInliner.h#L76-L78

And if you look at them, they're definitely heuristics: https://github.com/ethereum/solidity/blob/v0.8.20/libyul/optimiser/FullInliner.cpp#L174-L228

There are some things you could consider hard rules in there, but there are also fuzzy criteria that take into account the number of arguments or the number of instructions. These numbers were chosen mostly using some trial and error and intuition.

The way I worded it is because `FullInliner::shallInline()` is where I added that check (and it seems like the best place for that). You could even argue that this check by itself is a heuristic too because the inliner could just as well be inlining these things, it's an arbitrary choice not to.

In any case, I reworded it not to mention heuristics.

2023-07-18 09:52 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The bug has "high" severity in affected cases, but we deem the likelihood of it actually affecting deployed contracts as "very low".
You mean the `we think that the overall impact on real projects is low.` bit? That's the overall score.

2023-07-18 09:52 UTC, nikola-matic commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Code most likely to be broken by it is inline assembly, which normally constitutes a small
Sounds more natural to me, but is obviously not a deal breaker. Feel free to ignore.

2023-07-18 09:53 UTC, nikola-matic commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Therefore, while the bug can have severe consequences, we think that the overall impact on real
Because I like it better that way :D

2023-07-18 09:54 UTC, nikola-matic commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The bug has "high" severity in affected cases, but we deem the likelihood of it actually affecting deployed contracts as "very low".
Yes, that's what I meant, but I know get what you're saying as well, so yes, it's fine for it to remain `low` in this context (last line of blog post). Basically, the severity is high, the likelihood is very low, and thus the overall rating is low.

2023-07-18 10:59 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Therefore, while the bug can have severe consequences, we think that the overall impact on real
I think this one is fine as is :)

2023-07-18 11:00 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Code most likely to be broken by it is inline assembly, which normally constitutes a small
But I mean, this one seems actually incorrect :)

2023-07-18 11:22 UTC, nikola-matic approved these changes

2023-07-18 14:13 UTC, r0qs reviewed
Hey, I have some suggestions, let me know what you think :)

2023-07-18 14:13 UTC, r0qs commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +is a step that works best when the code is in the SSA form while at the same time destroying this property,
```suggestion
is a step that works best when the code is in the SSA form but it destroys this property,
```

2023-07-18 14:13 UTC, r0qs commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Even if `mload(0)` was evaluated before `mload(x)`, behavior of his code fragment would not change.
```suggestion
Even if `mload(0)` was evaluated before `mload(x)`, the behavior of this code fragment would not change.
```

2023-07-18 14:13 UTC, r0qs commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The introduction of side-effects, changes this:
```suggestion
However, the introduction of side-effects, changes this:
```

2023-07-18 14:38 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +However, the later introduction of a mechanism which allowed users to supply a custom sequence
Well, the sentence above already says `optimizer sequence` and I'm trying to avoid being too repetitive :)

2023-07-18 15:33 UTC, r0qs approved these changes

2023-07-18 15:35 UTC, nikola-matic commented
I guess we should wait for all of the prerequisite PRs to be merged (and for this PR to be squashed) before we merge.

2023-07-18 15:47 UTC, cameel commented
We're actually not merging it until we release :) Merging publishes the post to the blog.

Maybe I'll should just mark it as draft to avoid someone merging accidentally.

2023-07-18 15:59 UTC, NunoFilipeSantos requested changes
Some tweaks are needed.

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +On July 4, 2023, Robert Chen from OtterSec discovered a bug in Yul optimizer.
```suggestion
On July 4, 2023, Robert Chen from OtterSec discovered a bug in the Yul optimizer.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Also, certain language features are compiled from internal Yul code even by the legacy code generator.
```suggestion
Also, certain language features are compiled from internal Yul code, even by the legacy code generator.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +When the arguments are themselves function calls with side-effects, a change in the order may alter
```suggestion
When the arguments are themselves function calls with side effects, a change in the order may alter
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +However, the later introduction of a mechanism which allowed users to supply a custom sequence
```suggestion
However, the later introduction of a mechanism which allowed users to supply a custom sequence
```
```suggestion
However, the later introduction of a mechanism that allowed users to supply a custom sequence
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Initially the sequence was hard-coded in compiler's source code.
```suggestion
Initially, the sequence was hard-coded in compiler's source code.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Note that in the transformed code there is no ambiguity as to the order of side-effects
```suggestion
Note that in the transformed code, there is no ambiguity as to the order of side-effects
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +By itself this makes the code less optimal in most cases, because it increases the code size and
```suggestion
By itself, this makes the code less optimal in most cases because it increases the code size and
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +function boundaries), to better optimize the resulting code.
```suggestion
function boundaries) to better optimize the resulting code.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +When inlining a function, the inliner needs to ensure that its arguments will be evaluated properly.
```suggestion
When inlining a function, the inliner needs to ensure that its arguments will be appropriately evaluated.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +This would not decrease the effectiveness of the optimizer under normal circumstances, because the inliner
```suggestion
This would not decrease the effectiveness of the optimizer under normal circumstances because the inliner
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +arguments were identifiers and putting the argument expressions in an order different from the usual
```suggestion
arguments were identifiers, and putting the argument expressions in an order different from the usual
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The bug has potential to alter behavior of a contract in a very significant way.
```suggestion
The bug has the potential to alter the behavior of a contract in a very significant way.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Reordering reverts or returns may lead to storage writes, memory writes or event emissions not being performed.
```suggestion
Reordering reverts or returns may lead to storage writes, memory writes, or event emissions not being performed.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +sequence explicitly includes a step that actively transforms the code into non-expression-split form
```suggestion
sequence explicitly includes a step that actively transforms the code into a non-expression-split form
```

"a" or "the" missing

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +In absence of this, triggering the bug would likely require inline assembly or a contract written in pure Yul.
```suggestion
In the absence of this, triggering the bug would likely require inline assembly or a contract written in pure Yul.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The code generated by the IR pipeline is largely in the expression-split form, where each expression
```suggestion
The code generated by the IR pipeline is mainly in the expression-split form, where each expression
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +is assigned to a separate variable, because code in this form is very easy to generate.
```suggestion
is assigned to a separate variable because code in this form is very easy to generate.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +The compiler does generate calls in non-expression-split form in its own helper functions, but these
```suggestion
The compiler does generate calls in a non-expression-split form in its own helper functions, but these
```

a or the missing.

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +rarely have side-effects other than simple reverts.
```suggestion
rarely have side effects other than simple reverts.
```

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Anyone with enough knowledge to use it would be also likely to avoid inefficient sequences necessary
```suggestion
Anyone with enough knowledge to use it would also be likely to avoid inefficient sequences necessary
```

it's the other way around.

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Code most likely to be broken by it is inline assembly, which normally constitutes a small
```suggestion
The code most likely to be broken by it is inline assembly, which usually constitutes a small
```
Missing article.

2023-07-18 15:59 UTC, NunoFilipeSantos commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +Therefore, while the bug can have severe consequences, we think that the overall impact on real
```suggestion
Therefore, while the bug can have severe consequences, the overall impact on real
```

For a stronger voice.

2023-07-19 10:19 UTC, cameel commented on src/posts/2023-07-19-full-inliner-non-expression-split-argument-evaluation-order-bug.md
> +When inlining a function, the inliner needs to ensure that its arguments will be evaluated properly.
`appropriately evaluated` sounds a bit odd to me in this context. It's like it puts emphasis not on the thing I wanted emphasized.

Changed to "evaluated the same way as in the call".

2023-07-19 10:22 UTC, cameel commented
Tweaks applied.

2023-07-19 14:58 UTC, NunoFilipeSantos approved these changes
Ship it.

2023-07-19 15:17 UTC, merged